### ISSUE TITLE
Attempting to decompress genome before it is downloaded raises FileNotFoundException

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#307]
The uncaught exception is raised from line 129. I will create a PR removing the line.

https://github.com/TheJacksonLaboratory/Gopher/blob/ed50ff0fe04cea837da75b5e1c99eb97f2c7e421/src/main/java/gopher/io/GenomeGunZipper.java#L127-L133

```
java.io.FileNotFoundException: C:\Users\...\Dropbox\Charite\Dev\Gopher\null\chromFa.tar.gz (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at gopher.io.GenomeGunZipper.extractCanonicalChromosomes(GenomeGunZipper.java:83)
	at gopher.io.GenomeGunZipper.call(GenomeGunZipper.java:149)
	at gopher.io.GenomeGunZipper.call(GenomeGunZipper.java:24)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pnrobinson** [comment]
fixed
