### ISSUE TITLE
GOPHER unresponsive with large projects

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#338]
``GOPHER-0.5.5.jar`` was run on Windows 10 on a quad-core processor with options ``-Xms2g -Xmx12g``. 
I created viewpoints for all ``mm9`` genes with unbalanced segments. The project file is ~180 MB in size. GOPHER is hardly usable in this state. 

Attempting to display the first viewpoint (with >20 segments) took 6:41 minutes. GOPHER is unresponsive during this time:
```
[TRACE] 09-07-2018 18:48:00 [JavaFX Application Thread] (VPAnalysisPresenter.java:107) - Adding tab for row with Target: Ncf2, Chromosome: chr1, Genomic pos: 154647283 n selected 19
[TRACE] 09-07-2018 18:48:00 [JavaFX Application Thread] (VPAnalysisPresenter.java:228) - openTabs containsKey NO Ncf2
[TRACE] 09-07-2018 18:48:00 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to mm9 with default image width of 1600
[TRACE] 09-07-2018 18:48:38 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:49:14 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:49:54 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:50:35 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:51:03 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:51:47 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:52:17 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:53:01 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:53:24 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:54:12 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:54:41 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
```

``refreshVPTable()`` appears to be called for every segment that is visible in the table. When the user scrolls down a little in the table, ``refreshVPTable()`` is called and GOPHER is unresponsive again:

```
[TRACE] 09-07-2018 18:57:16 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:57:40 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:58:06 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:58:51 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 18:59:14 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects
[TRACE] 09-07-2018 19:00:00 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 25294 ViewPoint objects

```

Panel design summary:
![image](https://user-images.githubusercontent.com/5254933/45232989-a28f2800-b2d1-11e8-8004-8cde7e98fc27.png)

---

Possibly related:
@hansenp mentioned that performance on his computer appears to be much worse when running ``GOPHER-0.5.5.jar`` compared with running GOPHER from IntelliJ IDEA.

**Comment by hansenp** [comment]
I don't think that this is a memory issue. There seem to be lots of redundant calls of the function `refreshVPTable()`. For example, if the viewpoint tab is opened, it's not necessary to update the viewpoint table (right?). Furthermore, this is done multiple times when a viewpoint tab is opened probably for each digest (see above). If the viewpoint table is large, `refreshVPTable()` becomes very slow.

**Comment by pnrobinson** [comment]
I just ran gopher on the immune genes. refreshVPTable() gets called once at the very end (and only once)
```
[TRACE] 09-08-2018 07:52:41 [Thread-4] (Model.java:401) - setViewPoints: viewpointlist with size=1077
[TRACE] 09-08-2018 07:52:41 [JavaFX Application Thread] (GopherMainPresenter.java:1274) - Finished createViewPoints()
[TRACE] 09-08-2018 07:52:41 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
```
HOWEVER, when I then click on the first gene to open its viewpoint tab, refreshVPTable gets called multiple times
```
[TRACE] 09-08-2018 07:54:59 [JavaFX Application Thread] (VPAnalysisPresenter.java:107) - Adding tab for row with Target: ILDR2, Chromosome: chr1, Genomic pos: 166944561 n selected 9 
[TRACE] 09-08-2018 07:54:59 [JavaFX Application Thread] (VPAnalysisPresenter.java:228) - openTabs containsKey NO ILDR2
[TRACE] 09-08-2018 07:54:59 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
[TRACE] 09-08-2018 07:55:01 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:01 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:02 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:03 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:03 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:04 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:05 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:06 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:07 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:08 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:09 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
[TRACE] 09-08-2018 07:55:09 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 1077 ViewPoint objects
```
This is a BUG -- it is not obvious where it is coming from though

**Comment by pnrobinson** [comment]
refreshTable seems to be getting called once per segment? I tried with HindIII. If n=number of segments, then refreshTable is getting called n+1 times...

**Comment by pnrobinson** [comment]
I am not sure if these lines are needed in refreshTable -- they delete and then re-add all of the viewpoints (VpAnalysisPresenter, lines 367/368)

```
 viewPointTableView.getItems().clear(); /* clear previous rows, if any */
 viewPointTableView.getItems().addAll(vpl)
```

**Comment by pnrobinson** [comment]
Actually just scrolling the table causes refreshViewpoints to be called. Therefore, I think there is some actionevent that needs to be caught in the right way.

**Comment by pnrobinson** [comment]
I have gone through all of the code and it is not immediately obvious where this is coming from. I will try to find this bug by adding lots of logging statements -- there are not enough right now to figure out what the path of the code is.

**Comment by pnrobinson** [comment]
@steinha  Robin gets the prize for having found the bug.
In order to make sure the table does get refreshed when the user changes a view point, it was necessary to move the refreshTable down about 15 lines. Now everything seems to work and there are not multiple calls to refresh table!
I will check this in, @steinha @hansenp please test this -- if it is OK< then I think we can submit!

  if (!old_val.equals(new_val)) { // if the user has changed something, record that we have unsaved data
                        model.setClean(false);
                        analysisPresenter.refreshVPTable();
                    }

**Comment by pnrobinson** [comment]
Reopening until we have tested whether this is a 100% fix!

**Comment by pnrobinson** [comment]
initialize (and thus setCellValueFactory) should just get called once and this code does need to be executed once for each newly created checkbox.  I have checked this (set the logging level to TRACE in the help menu), and it seems that refreshViewpoint is being called only once and just when it should be. I am going to board a plane to Vienna soon and cannot test the promoterome with my laptop in the remaining time, but the 32 gene panel was fine. Please test!

**Comment by steinha** [comment]
True, ``initialize()`` and ``setCellValueFactory()`` are called once but the lambda expression argument to ``setCellValueFactory()`` is called many times (as far as I can tell any time the model changes for each visible checkbox, or if new checkboxes are scrolled into view).

This also affects small projects. Below is the log for a viewpoint with five segments when I added a logger line to the top inside the lambda expression. The first and fifth segment were initially not selected, the second to fourth segments were selected. 

```
[TRACE] 09-08-2018 22:23:03 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 not selected
[TRACE] 09-08-2018 22:23:03 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 not selected
[TRACE] 09-08-2018 22:23:03 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73830767-73864454 selected
[TRACE] 09-08-2018 22:23:03 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73864455-73867049 selected
[TRACE] 09-08-2018 22:23:03 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73867050-73877794 selected
[TRACE] 09-08-2018 22:23:03 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73877795-73898870 not selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 6 ViewPoint objects
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to mm9 with default image width of 1600
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 6 ViewPoint objects
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to mm9 with default image width of 1600
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73830767-73864454 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73864455-73867049 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73867050-73877794 selected
[TRACE] 09-08-2018 22:23:08 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73877795-73898870 not selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 6 ViewPoint objects
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to mm9 with default image width of 1600
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 6 ViewPoint objects
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to mm9 with default image width of 1600
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73795879-73830766 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73830767-73864454 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73864455-73867049 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73867050-73877794 selected
[TRACE] 09-08-2018 22:23:11 [JavaFX Application Thread] (ViewPointPresenter.java:254) - setCellValueFactory called for: 73877795-73898870 selected
```

**Comment by hansenp** [comment]
Tested for hg19, HindIII, default parameters on all protein coding genes. No errors occurred during creation viewpoints and GOPHER remained responsive when opening viewpoint tabs. Selection and deselection of digests is still slow but not too slow. Seems to be ok.

**Comment by hansenp** [comment]
Tested also for **hg38**, HindIII and `Allow unbalanced?`. I checked sorting by columns. No errors occurred. However, I noticed that viewpoints may become very large.

<img width="1348" alt="screen shot 2018-09-09 at 8 10 59 am" src="https://user-images.githubusercontent.com/10495485/45264293-614d6400-b408-11e8-9085-3399e6c9b5df.png">

We could add an example to the documentation and advise users to check this before ordering probes. But this is something that can be done after submission.

**Comment by pnrobinson** [comment]
Here is a new release
https://github.com/TheJacksonLaboratory/Gopher/releases/tag/0.5.6

**Comment by hansenp** [comment]
Now I tested hg38, **DpnII** and `Allow unbalanced?`. The viewpoints were created without errors. However, it took about 7 minutes until the analysis tab opened after creation. GOPHER was not responsive during this time and the table in the analysis tab remained empty. At the of the 7 minutes the following exception was thrown:

```
[TRACE] 09-09-2018 09:45:49 [Thread-8] (ExtendedViewPointCreationTask.java:142) - Created 26683 extended viewpoints
[TRACE] 09-09-2018 09:45:49 [Thread-8] (Model.java:401) - setViewPoints: viewpointlist with size=26683
[TRACE] 09-09-2018 09:45:49 [JavaFX Application Thread] (GopherMainPresenter.java:1274) - Finished createViewPoints()
Exception in thread "JavaFX Application Thread" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Integer.toString(Integer.java:401)
	at gopher.model.Design.getCaptureSize(Design.java:240)
	at gopher.gui.analysisPane.VPAnalysisPresenter.createListViewContent(VPAnalysisPresenter.java:344)
	at gopher.gui.analysisPane.VPAnalysisPresenter.updateListView(VPAnalysisPresenter.java:293)
	at gopher.gui.analysisPane.VPAnalysisPresenter.lambda$refreshVPTable$16(VPAnalysisPresenter.java:360)
	at gopher.gui.analysisPane.VPAnalysisPresenter$$Lambda$546/1822701583.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$49/610250873.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/1766822961.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by hansenp** [comment]
I checked my configuration and noticed that `-Xms2g -Xmx12g` were not set. I corrected this and now I will run this test again.

**Comment by steinha** [comment]
@hansenp, Have you tested toggling checkboxes without scrolling the table view? For me, each toggle increments by one the superfluous calls to ``refreshVPTable()``. Each call takes 30 to 40 seconds with the promoterome. So for the third toggle, GOPHER may need and be unresponsive for up to 2:00 minutes. See the annotated log from one run below. 

I will commit a PR in a moment that addresses this problem.

*Open viewpoint tab*:
```
[TRACE] 09-09-2018 16:02:01 [JavaFX Application Thread] (VPAnalysisPresenter.java:107) - Adding tab for row with Target: CRYZL2P-SEC16B, Chromosome: chr1, Genomic pos: 178007142 n selected 9 
[TRACE] 09-09-2018 16:02:01 [JavaFX Application Thread] (VPAnalysisPresenter.java:228) - openTabs containsKey NO CRYZL2P-SEC16B
[TRACE] 09-09-2018 16:02:01 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
```

*First toggle* – ``refreshVPTable()`` called once:
```
[TRACE] 09-09-2018 16:02:30 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26586 ViewPoint objects
[TRACE] 09-09-2018 16:02:30 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
```

*Second toggle* – ``refreshVPTable()`` called twice:
```
[TRACE] 09-09-2018 16:05:15 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26586 ViewPoint objects
[TRACE] 09-09-2018 16:05:15 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
[TRACE] 09-09-2018 16:05:58 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26586 ViewPoint objects
[TRACE] 09-09-2018 16:05:58 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
```

*Third toggle* – ``refreshVPTable()`` called thrice:
```
[TRACE] 09-09-2018 16:07:24 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26586 ViewPoint objects
[TRACE] 09-09-2018 16:07:24 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
[TRACE] 09-09-2018 16:07:55 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26586 ViewPoint objects
[TRACE] 09-09-2018 16:07:55 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
[TRACE] 09-09-2018 16:08:19 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26586 ViewPoint objects
[TRACE] 09-09-2018 16:08:19 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg19 with default image width of 1600
```

*Etc.*

**Comment by hansenp** [comment]
I repeated the test (hg38, DpnII and `Allow unbalanced?`) with `-Xms2g -Xmx12g`. This time there was exception and the analysis tab opened within reasonable time and contained all created viewpoints. Opening viewpoint tabs is fast. However, selection and deselection of digests requires between 1 and 2 minutes if I do it the first time. If I repeat this it takes longer due to additional calls of `refreshVPTable` (see previous comment).

**Comment by hansenp** [comment]
I tested again after the pull request was merged (hg38, DpnII and Allow unbalanced?, promoterome). The viewpoints are created without errors, opening viewpoint tabs is fast. Selection or deselection of a digest causes GOPHER to be unresponsive for about 25 seconds on my machine. This is the trace output when a digest is selected:
```
[TRACE] 09-10-2018 10:39:36 [JavaFX Application Thread] (VPAnalysisPresenter.java:366) - refreshVPTable: got a total of 26681 ViewPoint objects
[TRACE] 09-10-2018 10:39:36 [JavaFX Application Thread] (URLMaker.java:36) - setting genomebuild to hg38 with default image width of 1600
```
There are no superfluous calls of `refreshVPTable` anymore but 25 seconds unresponsiveness for each selected or deselected digest is a long time. The progress indicator with the wheel does not appear immediately after selection or deselection but only after 20 seconds.

**Comment by hansenp** [comment]
I'm not sure if this is already clear, but this part of the lambda expression in ViewPointPresenter
```

       isSelectedTableColumn.setCellValueFactory(cdf -> {
            // if we get here, the user has selected or deselected the checkbox
            //this.viewpoint.setManuallyRevised();
            //this.analysisPresenter.refreshVPTable();
            Segment segment = cdf.getValue().getSegment();
            CheckBox checkBox = cdf.getValue().getCheckBox();
            ChangeListener changeListener = cdf.getValue().getChangeListener();
            if (segment.isUnselectable()) {
                checkBox.setDisable(true);
            } else if (segment.isSelected()) {// inspect state of the segment and initialize CheckBox state accordingly
                checkBox.setSelected(true);
            }
            if (changeListener == null) {
```

Seems to be executed (number of all digests)+4 times. If I test for the 3 human example genes.

**Comment by hansenp** [comment]
I created viewpoints for 10,000 gene symbols and started GOPHER in debug mode. I found out that GOPHER spends the most of the time in this piece of code:

```
        @Override
        public void mouseEvent(EventType<MouseEvent> type, double x, double y, double screenX, double screenY,
                               MouseButton button, boolean popupTrigger, boolean synthesized,
                               boolean shiftDown, boolean controlDown, boolean altDown, boolean metaDown,
                               boolean primaryDown, boolean middleDown, boolean secondaryDown)
        {
            MouseEvent mouseEvent = new MouseEvent(type, x, y, screenX, screenY, button,
                    0, // click count will be adjusted by clickGenerator later anyway
                    shiftDown, controlDown, altDown, metaDown,
                    primaryDown, middleDown, secondaryDown, synthesized, popupTrigger, false, null);
            impl_processMouseEvent(mouseEvent);
        }
```
which is in the class `Scene`. This function is called after `refreshVPTable` has already finished. I also measured the time that is spend in `refreshVPTable` using `System.nanoTime()` (not sure if this is useful) and could not find big differences for different numbers of viewpoints and segments.

**Comment by pnrobinson** [comment]
strange. 
Maybe we can catch some mouse events with code like thid
```
@Override
    public void handle(MouseEvent t) {
        //System.out.println("Line has been clicked");
        t.consume(); // consume event -> no further propagation
    }
```
to stop the propagation. Some mouse events mught be valida work thous.

**Comment by steinha** [comment]
When performance with the promoterome is sluggish, maybe it would make sense to swap the ``All protein-coding genes`` button with the ``Enter BED file`` button.

![image](https://user-images.githubusercontent.com/5254933/45349531-cb553d00-b5b1-11e8-86ed-7bab5be30d18.png)

**Comment by hansenp** [comment]
No, I don't think this is a good idea. _Target gene_ list and _All protein-coding genes_ are linked with regard to content (promoters). Therefore, they should be side by side.

The _All protein-coding genes_ button is an invitation to test GOPHER for a large number of targets. I think we either have to solve this issue or completely remove this button.

**Comment by hansenp** [comment]
I tested the released version v0.3.9 of GOPHER. I tested selecting and deselecting of segments. Even though this version still has all the redundant calls of `refreshVPTable` it seems to be more responsive. In contrast to the current version the progress indicator with the wheel appears immediately after selection.

![peek 2018-09-11 19-02](https://user-images.githubusercontent.com/10495485/45374994-07a98d00-b5f4-11e8-984a-8ab08d64e97a.gif)


I opened the same project with the current version and it was much slower. Therefore, I believe that what we are struggling with now was introduced after v0.3.9.

**Comment by hansenp** [comment]
I checked additional releases. It seems that the bug with the extreme unresponsiveness has been introduced with release 0.5.1. When I compile the package there are additional warnings that do not occur for release 0.5.0, which seems to bu unaffected:

```
[INFO] Including org.ow2.asm:asm-util:jar:6.0_BETA in the shaded jar.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
[WARNING] javax.inject-1.jar, sisu-inject-bean-1.4.2.jar define 6 overlapping classes: 
[WARNING]   - javax.inject.Inject
[WARNING]   - javax.inject.Singleton
[WARNING]   - javax.inject.Scope
[WARNING]   - javax.inject.Named
[WARNING]   - javax.inject.Provider
[WARNING]   - javax.inject.Qualifier
[WARNING] aether-util-0.9.0.M2.jar, maven-artifact-transfer-0.9.1.jar define 10 overlapping classes: 
[WARNING]   - org.eclipse.aether.util.filter.AndDependencyFilter
[WARNING]   - org.eclipse.aether.util.artifact.SubArtifact
[WARNING]   - org.eclipse.aether.util.filter.NotDependencyFilter
[WARNING]   - org.eclipse.aether.util.filter.PatternInclusionsDependencyFilter
[WARNING]   - org.eclipse.aether.util.filter.PatternExclusionsDependencyFilter
[WARNING]   - org.eclipse.aether.util.filter.DependencyFilterUtils
[WARNING]   - org.eclipse.aether.util.filter.AbstractPatternDependencyFilter
[WARNING]   - org.eclipse.aether.util.filter.ScopeDependencyFilter
[WARNING]   - org.eclipse.aether.util.filter.OrDependencyFilter
[WARNING]   - org.eclipse.aether.util.filter.ExclusionsDependencyFilter
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/ 
```
I will further narrow down the precise commit in which the bug was introduced.

**Comment by hansenp** [comment]
I improved the function `design.getCaptureSize()`. Selection or deselection of a segment now takes 5 seconds for a project with 18,000 viewpoints on my computer.

Opening of large projects is still slow. This takes about 1 minute.

**Comment by pnrobinson** [comment]
I think that the performance of GOPHER is now satisfactory. I guess it is to be expected that a large project will take time to open -- the ser file is about 180MB and all of that has to be re-vivified into Java objects. After discussion, we will close this issue because there were so many different items, many of which have been addressed. If there continue to be performance issues, let's open new more specific items.
