### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#339]
GOPHER took a little over one minute to do all of the promoters on my box. However, there were two errors during the processing (SULT1C2, OPRM1) and then only one gene was shown on the analysis tab, probably because of this crash
```
$ java -Xms2g -Xmx6g -jar target/GOPHER-0.5.5.jar 
[ERROR] 09-07-2018 13:43:54 [ForkJoinPool.commonPool-worker-1] (ViewPoint.java:607) - SULT1C2 At least one digest must contain 'genomicPos' (chr2:108905095)
[ERROR] 09-07-2018 13:44:27 [ForkJoinPool.commonPool-worker-2] (ViewPoint.java:607) - OPRM1 At least one digest must contain 'genomicPos' (chr6:154410897)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at gopher.model.Design.lambda$calculateDesignParameters$0(Design.java:164)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at gopher.model.Design.calculateDesignParameters(Design.java:163)
	at gopher.gui.analysisPane.VPAnalysisPresenter.createListViewContent(VPAnalysisPresenter.java:308)
	at gopher.gui.analysisPane.VPAnalysisPresenter.updateListView(VPAnalysisPresenter.java:293)
	at gopher.gui.analysisPane.VPAnalysisPresenter.lambda$refreshVPTable$16(VPAnalysisPresenter.java:360)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by pnrobinson** [comment]
The culprit was this
```
 public List<Segment> getActiveSegments() {
        if (restrictionSegmentList==null) {
            logger.error(String.format("Error-- null list of restriction segments for %s",getTargetName()));
            return new ArrayList<>();/* return empty list.*/
        }
        //return a List of all selected segments
        return this.restrictionSegmentList.stream().filter(Segment::isSelected)).collect(Collectors.toList());
    }
```
apparently the restrictionSegment list was returning a null pointer somewhere and the call to isSelected caused the null pounter exception.
I changed it to this and everything was ok:
```
   return this.restrictionSegmentList.stream().filter(s -> (s!=null && s.isSelected())).collect(Collectors.toList());
```
