### ISSUE TITLE
Null Pointer

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#351]
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at gopher.model.Design.lambda$calculateDesignParameters$0(Design.java:164)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at gopher.model.Design.calculateDesignParameters(Design.java:163)
	at gopher.gui.analysisPane.VPAnalysisPresenter.createListViewContent(VPAnalysisPresenter.java:308)
	at gopher.gui.analysisPane.VPAnalysisPresenter.updateListView(VPAnalysisPresenter.java:293)
	at gopher.gui.analysisPane.VPAnalysisPresenter.lambda$refreshVPTable$16(VPAnalysisPresenter.java:360)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by pnrobinson** [comment]
Not sure where this came from, but the error is not reproducible.
